version: 0.2

env:
  variables:
    ECR_REPOSITORY: 267375937715.dkr.ecr.ap-northeast-1.amazonaws.com/test-ecr
  secrets-manager:
    DOCKERHUB_USERNAME: "dockerEnv:DOCKERHUB_USERNAME" # JSON内の'username'キーの値を取得
    DOCKERHUB_PASSWORD: "dockerEnv:DOCKERHUB_PASSWORD" # JSON内の'password'キーの値を取得
    
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t container-test-app .
      - docker tag container-test-app:latest ${ECR_REPOSITORY}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:latest
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "container-test-app",
            "imageUri": "'${ECR_REPOSITORY}':latest"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.

artifacts:
  files:
    - imagedefinitions.json
